name: update

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update:
    if: github.repository == 'zeux/volk'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: update
      run: |
        python3 generate.py >version.txt
        echo "VOLK_VERSION=`cat version.txt`" >> $GITHUB_ENV
        rm version.txt
    - name: create pr
      uses: peter-evans/create-pull-request@v6
      with:
        branch: update/${{env.VOLK_VERSION}}
        delete-branch: true
        commit-message: Update to 1.4.${{env.VOLK_VERSION}}
        title: Update to 1.4.${{env.VOLK_VERSION}}
        author: GitHub <noreply@github.com>
    - name: enable pr automerge
      run: |
        sleep 60
        gh pr merge --merge --auto ${{env.PULL_REQUEST_NUMBER}}
      env:
        GH_TOKEN: ${{ github.token }}
      continue-on-error: true
