import os

content = """/*
 * Geforce NV2A PGRAPH GLSL Shader Generator (Decoupled Pre-compiled Template)
 */

#include "qemu/osdep.h"
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <assert.h>

#include "common.h"
#include "vsh.h"
#include "vsh-prog.h"

static const char* vsh_header =
    "\\n"
    "int A0 = 0;\\n"
    "\\n"
    "/* Used to emulate concurrency of paired MAC+ILU instructions */\\n"
    "vec4 _temp_vec;\\n"
    "int _temp_addr;\\n"
    "\\n"
    "/* Converts the input to vec4, pads with last component */\\n"
    "vec4 _in(float v) { return vec4(v); }\\n"
    "vec4 _in(vec2 v) { return v.xyyy; }\\n"
    "vec4 _in(vec3 v) { return v.xyzz; }\\n"
    "vec4 _in(vec4 v) { return v.xyzw; }\\n"
    "\\n"
    "#define INFINITY (1.0 / 0.0)\\n"
    "\\n"
    "#define MOV(dest, mask, src) dest.mask = _MOV(_in(src)).mask\\n"
    "vec4 _MOV(vec4 src) { return src; }\\n"
    "\\n"
    "#define MUL(dest, mask, src0, src1) dest.mask = _MUL(_in(src0), _in(src1)).mask\\n"
    "vec4 _MUL(vec4 src0, vec4 src1) {\\n"
    "  vec4 zero_components = sign(NaNToOne(src0)) * sign(NaNToOne(src1));\\n"
    "  vec4 ret = src0 * src1;\\n"
    "  if (zero_components.x == 0.0) { ret.x = 0.0; }\\n"
    "  if (zero_components.y == 0.0) { ret.y = 0.0; }\\n"
    "  if (zero_components.z == 0.0) { ret.z = 0.0; }\\n"
    "  if (zero_components.w == 0.0) { ret.w = 0.0; }\\n"
    "  return ret;\\n"
    "}\\n"
    "\\n"
    "#define ADD(dest, mask, src0, src1) dest.mask = _ADD(_in(src0), _in(src1)).mask\\n"
    "vec4 _ADD(vec4 src0, vec4 src1) { return src0 + src1; }\\n"
    "\\n"
    "#define MAD(dest, mask, src0, src1, src2) dest.mask = _MAD(_in(src0), _in(src1), _in(src2)).mask\\n"
    "vec4 _MAD(vec4 src0, vec4 src1, vec4 src2) { return _MUL(src0, src1) + src2; }\\n"
    "\\n"
    "#define DP3(dest, mask, src0, src1) dest.mask = _DP3(_in(src0), _in(src1)).mask\\n"
    "vec4 _DP3(vec4 src0, vec4 src1) { return vec4(dot(src0.xyz, src1.xyz)); }\\n"
    "\\n"
    "#define DPH(dest, mask, src0, src1) dest.mask = _DPH(_in(src0), _in(src1)).mask\\n"
    "vec4 _DPH(vec4 src0, vec4 src1) { return vec4(dot(vec4(src0.xyz, 1.0), src1)); }\\n"
    "\\n"
    "#define DP4(dest, mask, src0, src1) dest.mask = _DP4(_in(src0), _in(src1)).mask\\n"
    "vec4 _DP4(vec4 src0, vec4 src1) { return vec4(dot(src0, src1)); }\\n"
    "\\n"
    "#define DST(dest, mask, src0, src1) dest.mask = _DST(_in(src0), _in(src1)).mask\\n"
    "vec4 _DST(vec4 src0, vec4 src1) { return vec4(1.0, src0.y * src1.y, src0.z, src1.w); }\\n"
    "\\n"
    "#define MIN(dest, mask, src0, src1) dest.mask = _MIN(_in(src0), _in(src1)).mask\\n"
    "vec4 _MIN(vec4 src0, vec4 src1) { return min(src0, src1); }\\n"
    "\\n"
    "#define MAX(dest, mask, src0, src1) dest.mask = _MAX(_in(src0), _in(src1)).mask\\n"
    "vec4 _MAX(vec4 src0, vec4 src1) { return max(src0, src1); }\\n"
    "\\n"
    "#define SLT(dest, mask, src0, src1) dest.mask = _SLT(_in(src0), _in(src1)).mask\\n"
    "vec4 _SLT(vec4 src0, vec4 src1) { return vec4(lessThan(src0, src1)); }\\n"
    "\\n"
    "#define ARL(dest, src) dest = _ARL(_in(src).x)\\n"
    "int _ARL(float src) { return int(floor(src + 0.001)); }\\n"
    "\\n"
    "#define SGE(dest, mask, src0, src1) dest.mask = _SGE(_in(src0), _in(src1)).mask\\n"
    "vec4 _SGE(vec4 src0, vec4 src1) { return vec4(greaterThanEqual(src0, src1)); }\\n"
    "\\n"
    "#define RCP(dest, mask, src) dest.mask = _RCP(_in(src).x).mask\\n"
    "vec4 _RCP(float src) { return vec4(1.0 / src); }\\n"
    "\\n"
    "#define RCC(dest, mask, src) dest.mask = _RCC(_in(src).x).mask\\n"
    "vec4 _RCC(float src) { float t = clampAwayZeroInf(1.0 / src); return vec4(t); }\\n"
    "\\n"
    "#define RSQ(dest, mask, src) dest.mask = _RSQ(_in(src).x).mask\\n"
    "vec4 _RSQ(float src) {\\n"
    "  if (src == 0.0) { return vec4(INFINITY); }\\n"
    "  if (isinf(src)) { return vec4(0.0); }\\n"
    "  return vec4(inversesqrt(abs(src)));\\n"
    "}\\n"
    "\\n"
    "#define EXP(dest, mask, src) dest.mask = _EXP(_in(src).x).mask\\n"
    "vec4 _EXP(float src) {\\n"
    "  vec4 result;\\n"
    "  result.x = exp2(floor(src));\\n"
    "  result.y = src - floor(src);\\n"
    "  result.z = exp2(src);\\n"
    "  result.w = 1.0;\\n"
    "  return result;\\n"
    "}\\n"
    "\\n"
    "#define LOG(dest, mask, src) dest.mask = _LOG(_in(src).x).mask\\n"
    "vec4 _LOG(float src) {\\n"
    "  float tmp = abs(src);\\n"
    "  if (tmp == 0.0) { return vec4(-INFINITY, 1.0f, -INFINITY, 1.0f); }\\n"
    "  vec4 result;\\n"
    "  result.x = floor(log2(tmp));\\n"
    "  result.y = tmp / exp2(floor(log2(tmp)));\\n"
    "  result.z = log2(tmp);\\n"
    "  result.w = 1.0;\\n"
    "  return result;\\n"
    "}\\n"
    "\\n"
    "#define LIT(dest, mask, src) dest.mask = _LIT(_in(src)).mask\\n"
    "vec4 _LIT(vec4 src) {\\n"
    "  vec4 s = src;\\n"
    "  float epsilon = 1.0 / 256.0;\\n"
    "  s.w = clamp(s.w, -(128.0 - epsilon), 128.0 - epsilon);\\n"
    "  s.x = max(s.x, 0.0);\\n"
    "  s.y = max(s.y, 0.0);\\n"
    "  vec4 t = vec4(1.0, 0.0, 0.0, 1.0);\\n"
    "  t.y = s.x;\\n"
    "  t.z = (s.x > 0.0) ? exp2(s.w * log2(s.y)) : 0.0;\\n"
    "  return t;\\n"
    "}\\n";

static const char* vsh_prog_interpreter =
    "  vec4 R[16];\\n"
    "  for (int i=0; i<16; i++) { R[i] = vec4(0.0); }\\n"
    "  vec4 V[16];\\n"
    "  V[0] = v0; V[1] = v1; V[2] = v2; V[3] = v3; V[4] = v4; V[5] = v5;\\n"
    "  V[6] = v6; V[7] = v7; V[8] = v8; V[9] = v9; V[10] = v10; V[11] = v11;\\n"
    "  V[12] = v12; V[13] = v13; V[14] = v14; V[15] = v15;\\n"
    "\\n"
    "  for (int pc=0; pc < programLength; pc++) {\\n"
    "      uvec4 tk = programData[pc];\\n"
    "      uint ilu = bitfieldExtract(tk.y, 25, 3);\\n"
    "      uint mac = bitfieldExtract(tk.y, 21, 4);\\n"
    "      if (mac == 0u && ilu == 0u) continue;\\n"
    "\\n"
    "      uint c_mux = bitfieldExtract(tk.w, 28, 2);\\n"
    "      uint c_neg = bitfieldExtract(tk.z, 10, 1);\\n"
    "      uvec4 c_swz = uvec4(bitfieldExtract(tk.z, 8, 2), bitfieldExtract(tk.z, 6, 2), bitfieldExtract(tk.z, 4, 2), bitfieldExtract(tk.z, 2, 2));\\n"
    "      if (ilu >= 2u && ilu <= 6u) {\\n"
    "          c_swz.y = c_swz.x; c_swz.z = c_swz.x; c_swz.w = c_swz.x;\\n"
    "      }\\n"
    "      uint c_r = (bitfieldExtract(tk.z, 0, 2) << 2) | bitfieldExtract(tk.w, 30, 2);\\n"
    "\\n"
    "      vec4 src_c = vec4(0.0);\\n"
    "      if (c_mux == 1u) { if (c_r == 12u) src_c = oPos; else src_c = R[c_r]; }\\n"
    "      else if (c_mux == 2u) src_c = V[c_r];\\n"
    "      else if (c_mux == 3u) {\\n"
    "          uint c_idx = bitfieldExtract(tk.y, 13, 8);\\n"
    "          int reg_num = ((((int(c_idx) >> 5) & 7) - 3) * 32) + int(c_idx & 31) + 96;\\n"
    "          if (bitfieldExtract(tk.w, 1, 1) > 0u) src_c = c[A0 + reg_num];\\n"
    "          else src_c = c[reg_num];\\n"
    "      }\\n"
    "      vec4 in_c = src_c;\\n"
    "      src_c.x = c_swz.x == 0u ? in_c.x : (c_swz.x == 1u ? in_c.y : (c_swz.x == 2u ? in_c.z : in_c.w));\\n"
    "      src_c.y = c_swz.y == 0u ? in_c.x : (c_swz.y == 1u ? in_c.y : (c_swz.y == 2u ? in_c.z : in_c.w));\\n"
    "      src_c.z = c_swz.z == 0u ? in_c.x : (c_swz.z == 1u ? in_c.y : (c_swz.z == 2u ? in_c.z : in_c.w));\\n"
    "      src_c.w = c_swz.w == 0u ? in_c.x : (c_swz.w == 1u ? in_c.y : (c_swz.w == 2u ? in_c.z : in_c.w));\\n"
    "      if (c_neg > 0u) src_c = -src_c;\\n"
    "\\n"
    "      vec4 src_a = vec4(0.0);\\n"
    "      if (mac != 0u) {\\n"
    "         uint a_mux = bitfieldExtract(tk.z, 26, 2);\\n"
    "         if (a_mux != 0u) {\\n"
    "             uint a_neg = bitfieldExtract(tk.y, 8, 1);\\n"
    "             uvec4 a_swz = uvec4(bitfieldExtract(tk.y, 6, 2), bitfieldExtract(tk.y, 4, 2), bitfieldExtract(tk.y, 2, 2), bitfieldExtract(tk.y, 0, 2));\\n"
    "             uint a_r = bitfieldExtract(tk.z, 28, 4);\\n"
    "             vec4 input_a = vec4(0.0);\\n"
    "             if (a_mux == 1u) { if (a_r == 12u) input_a = oPos; else input_a = R[a_r]; }\\n"
    "             else if (a_mux == 2u) input_a = V[a_r];\\n"
    "             else if (a_mux == 3u) {\\n"
    "                  uint c_idx = bitfieldExtract(tk.y, 13, 8);\\n"
    "                  int reg_num = ((((int(c_idx) >> 5) & 7) - 3) * 32) + int(c_idx & 31) + 96;\\n"
    "                  if (bitfieldExtract(tk.w, 1, 1) > 0u) input_a = c[A0 + reg_num];\\n"
    "                  else input_a = c[reg_num];\\n"
    "             }\\n"
    "             src_a.x = a_swz.x == 0u ? input_a.x : (a_swz.x == 1u ? input_a.y : (a_swz.x == 2u ? input_a.z : input_a.w));\\n"
    "             src_a.y = a_swz.y == 0u ? input_a.x : (a_swz.y == 1u ? input_a.y : (a_swz.y == 2u ? input_a.z : input_a.w));\\n"
    "             src_a.z = a_swz.z == 0u ? input_a.x : (a_swz.z == 1u ? input_a.y : (a_swz.z == 2u ? input_a.z : input_a.w));\\n"
    "             src_a.w = a_swz.w == 0u ? input_a.x : (a_swz.w == 1u ? input_a.y : (a_swz.w == 2u ? input_a.z : input_a.w));\\n"
    "             if (a_neg > 0u) src_a = -src_a;\\n"
    "         }\\n"
    "      }\\n"
    "\\n"
    "      vec4 src_b = vec4(0.0);\\n"
    "      if (mac != 0u) {\\n"
    "         uint b_mux = bitfieldExtract(tk.z, 11, 2);\\n"
    "         if (b_mux != 0u) {\\n"
    "             uint b_neg = bitfieldExtract(tk.z, 25, 1);\\n"
    "             uvec4 b_swz = uvec4(bitfieldExtract(tk.z, 23, 2), bitfieldExtract(tk.z, 21, 2), bitfieldExtract(tk.z, 19, 2), bitfieldExtract(tk.z, 17, 2));\\n"
    "             uint b_r = bitfieldExtract(tk.z, 13, 4);\\n"
    "             vec4 input_b = vec4(0.0);\\n"
    "             if (b_mux == 1u) { if (b_r == 12u) input_b = oPos; else input_b = R[b_r]; }\\n"
    "             else if (b_mux == 2u) input_b = V[b_r];\\n"
    "             else if (b_mux == 3u) {\\n"
    "                  uint c_idx = bitfieldExtract(tk.y, 13, 8);\\n"
    "                  int reg_num = ((((int(c_idx) >> 5) & 7) - 3) * 32) + int(c_idx & 31) + 96;\\n"
    "                  if (bitfieldExtract(tk.w, 1, 1) > 0u) input_b = c[A0 + reg_num];\\n"
    "                  else input_b = c[reg_num];\\n"
    "             }\\n"
    "             src_b.x = b_swz.x == 0u ? input_b.x : (b_swz.x == 1u ? input_b.y : (b_swz.x == 2u ? input_b.z : input_b.w));\\n"
    "             src_b.y = b_swz.y == 0u ? input_b.x : (b_swz.y == 1u ? input_b.y : (b_swz.y == 2u ? input_b.z : input_b.w));\\n"
    "             src_b.z = b_swz.z == 0u ? input_b.x : (b_swz.z == 1u ? input_b.y : (b_swz.z == 2u ? input_b.z : input_b.w));\\n"
    "             src_b.w = b_swz.w == 0u ? input_b.x : (b_swz.w == 1u ? input_b.y : (b_swz.w == 2u ? input_b.z : input_b.w));\\n"
    "             if (b_neg > 0u) src_b = -src_b;\\n"
    "         }\\n"
    "      }\\n"
    "\\n"
    "      vec4 mac_out = vec4(0.0);\\n"
    "      if (mac == 1u) mac_out = _MOV(src_a);\\n"
    "      else if (mac == 2u) mac_out = _MUL(src_a, src_b);\\n"
    "      else if (mac == 3u) mac_out = _ADD(src_a, src_c);\\n"
    "      else if (mac == 4u) mac_out = _MAD(src_a, src_b, src_c);\\n"
    "      else if (mac == 5u) mac_out = _DP3(src_a, src_b);\\n"
    "      else if (mac == 6u) mac_out = _DPH(src_a, src_b);\\n"
    "      else if (mac == 7u) mac_out = _DP4(src_a, src_b);\\n"
    "      else if (mac == 8u) mac_out = _DST(src_a, src_b);\\n"
    "      else if (mac == 9u) mac_out = _MIN(src_a, src_b);\\n"
    "      else if (mac == 10u) mac_out = _MAX(src_a, src_b);\\n"
    "      else if (mac == 11u) mac_out = _SLT(src_a, src_b);\\n"
    "      else if (mac == 12u) mac_out = _SGE(src_a, src_b);\\n"
    "      else if (mac == 13u) A0 = _ARL(src_a.x);\\n"
    "\\n"
    "      vec4 ilu_out = vec4(0.0);\\n"
    "      if (ilu == 1u) ilu_out = _MOV(src_c);\\n"
    "      else if (ilu == 2u) ilu_out = _RCP(src_c.x);\\n"
    "      else if (ilu == 3u) ilu_out = _RCC(src_c.x);\\n"
    "      else if (ilu == 4u) ilu_out = _RSQ(src_c.x);\\n"
    "      else if (ilu == 5u) ilu_out = _EXP(src_c.x);\\n"
    "      else if (ilu == 6u) ilu_out = _LOG(src_c.x);\\n"
    "      else if (ilu == 7u) ilu_out = _LIT(src_c);\\n"
    "\\n"
    "      uint out_r = bitfieldExtract(tk.w, 20, 4);\\n"
    "      uint out_orb = bitfieldExtract(tk.w, 11, 1);\\n"
    "      uint out_addr = bitfieldExtract(tk.w, 3, 8) & 0xFu;\\n"
    "      uint out_mux = bitfieldExtract(tk.w, 2, 1);\\n"
    "      uint out_o_mask = bitfieldExtract(tk.w, 12, 4);\\n"
    "      uint mac_mask = bitfieldExtract(tk.w, 24, 4);\\n"
    "      uint ilu_mask = bitfieldExtract(tk.w, 16, 4);\\n"
    "\\n"
    "      bool use_temp_var = false;\\n"
    "      uint paired_mac_out_r = out_r;\\n"
    "      uint paired_ilu_out_r = out_r;\\n"
    "      if (out_mux == 0u && ilu != 0u) {\\n"
    "          use_temp_var = true;\\n"
    "          if (out_r == 1u) mac_mask = 0u;\\n"
    "      } else if (out_mux == 1u && mac != 0u) {\\n"
    "          paired_ilu_out_r = 1u;\\n"
    "      }\\n"
    "\\n"
    "      if (mac != 0u && mac != 13u) {\\n"
    "          if (mac_mask != 0u) {\\n"
    "              if ((mac_mask & 8u)!=0u) R[paired_mac_out_r].x = mac_out.x;\\n"
    "              if ((mac_mask & 4u)!=0u) R[paired_mac_out_r].y = mac_out.y;\\n"
    "              if ((mac_mask & 2u)!=0u) R[paired_mac_out_r].z = mac_out.z;\\n"
    "              if ((mac_mask & 1u)!=0u) R[paired_mac_out_r].w = mac_out.w;\\n"
    "              if (paired_mac_out_r == 12u) {\\n"
    "                  if ((mac_mask & 8u)!=0u) oPos.x = mac_out.x;\\n"
    "                  if ((mac_mask & 4u)!=0u) oPos.y = mac_out.y;\\n"
    "                  if ((mac_mask & 2u)!=0u) oPos.z = mac_out.z;\\n"
    "                  if ((mac_mask & 1u)!=0u) oPos.w = mac_out.w;\\n"
    "              }\\n"
    "          }\\n"
    "          if (out_mux == 0u && out_o_mask != 0u && out_orb == 1u) {\\n"
    "              if (out_addr == 0u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oPos.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oPos.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oPos.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oPos.w = mac_out.w;\\n"
    "              } else if (out_addr == 3u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oD0.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oD0.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oD0.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oD0.w = mac_out.w;\\n"
    "              } else if (out_addr == 4u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oD1.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oD1.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oD1.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oD1.w = mac_out.w;\\n"
    "              } else if (out_addr == 5u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oFog.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oFog.y = mac_out.x;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oFog.z = mac_out.x;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oFog.w = mac_out.x;\\n"
    "              } else if (out_addr == 6u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oPts.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oPts.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oPts.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oPts.w = mac_out.w;\\n"
    "              } else if (out_addr == 7u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oB0.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oB0.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oB0.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oB0.w = mac_out.w;\\n"
    "              } else if (out_addr == 8u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oB1.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oB1.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oB1.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oB1.w = mac_out.w;\\n"
    "              } else if (out_addr == 9u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT0.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT0.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT0.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT0.w = mac_out.w;\\n"
    "              } else if (out_addr == 10u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT1.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT1.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT1.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT1.w = mac_out.w;\\n"
    "              } else if (out_addr == 11u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT2.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT2.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT2.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT2.w = mac_out.w;\\n"
    "              } else if (out_addr == 12u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT3.x = mac_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT3.y = mac_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT3.z = mac_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT3.w = mac_out.w;\\n"
    "              }\\n"
    "          }\\n"
    "      }\\n"
    "      if (ilu != 0u) {\\n"
    "          if (ilu_mask != 0u) {\\n"
    "              if ((ilu_mask & 8u)!=0u) R[paired_ilu_out_r].x = ilu_out.x;\\n"
    "              if ((ilu_mask & 4u)!=0u) R[paired_ilu_out_r].y = ilu_out.y;\\n"
    "              if ((ilu_mask & 2u)!=0u) R[paired_ilu_out_r].z = ilu_out.z;\\n"
    "              if ((ilu_mask & 1u)!=0u) R[paired_ilu_out_r].w = ilu_out.w;\\n"
    "              if (paired_ilu_out_r == 12u) {\\n"
    "                  if ((ilu_mask & 8u)!=0u) oPos.x = ilu_out.x;\\n"
    "                  if ((ilu_mask & 4u)!=0u) oPos.y = ilu_out.y;\\n"
    "                  if ((ilu_mask & 2u)!=0u) oPos.z = ilu_out.z;\\n"
    "                  if ((ilu_mask & 1u)!=0u) oPos.w = ilu_out.w;\\n"
    "              }\\n"
    "          }\\n"
    "          if (out_mux == 1u && out_o_mask != 0u && out_orb == 1u) {\\n"
    "              if (out_addr == 0u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oPos.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oPos.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oPos.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oPos.w = ilu_out.w;\\n"
    "              } else if (out_addr == 3u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oD0.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oD0.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oD0.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oD0.w = ilu_out.w;\\n"
    "              } else if (out_addr == 4u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oD1.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oD1.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oD1.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oD1.w = ilu_out.w;\\n"
    "              } else if (out_addr == 5u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oFog.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oFog.y = ilu_out.x;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oFog.z = ilu_out.x;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oFog.w = ilu_out.x;\\n"
    "              } else if (out_addr == 6u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oPts.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oPts.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oPts.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oPts.w = ilu_out.w;\\n"
    "              } else if (out_addr == 7u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oB0.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oB0.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oB0.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oB0.w = ilu_out.w;\\n"
    "              } else if (out_addr == 8u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oB1.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oB1.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oB1.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oB1.w = ilu_out.w;\\n"
    "              } else if (out_addr == 9u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT0.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT0.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT0.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT0.w = ilu_out.w;\\n"
    "              } else if (out_addr == 10u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT1.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT1.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT1.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT1.w = ilu_out.w;\\n"
    "              } else if (out_addr == 11u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT2.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT2.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT2.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT2.w = ilu_out.w;\\n"
    "              } else if (out_addr == 12u) {\\n"
    "                 if ((out_o_mask & 8u)!=0u) oT3.x = ilu_out.x;\\n"
    "                 if ((out_o_mask & 4u)!=0u) oT3.y = ilu_out.y;\\n"
    "                 if ((out_o_mask & 2u)!=0u) oT3.z = ilu_out.z;\\n"
    "                 if ((out_o_mask & 1u)!=0u) oT3.w = ilu_out.w;\\n"
    "              }\\n"
    "          }\\n"
    "      }\\n"
    "\\n"
    "      if (bitfieldExtract(tk.w, 0, 1) != 0u) break;\\n"
    "  }\\n"
    "  oPos.xy = roundScreenCoords(oPos.xy);\\n"
    "  oPos.w = clampAwayZeroInf(oPos.w);\\n"
    "  vec4 vtxPos = oPos;\\n"
    "  oPos.xy = (2.0f * oPos.xy - surfaceSize) / surfaceSize;\\n"
    "  oPos.z = oPos.z / clipRange.y;\\n"
    "  oPos.xyz *= oPos.w;\\n";

void pgraph_glsl_gen_vsh_prog(uint16_t version, const uint32_t *tokens,
                              unsigned int length, MString *header,
                              MString *body)
{
    mstring_append(header, vsh_header);
    mstring_append(body, vsh_prog_interpreter);
}
"""

with open('hw/xbox/nv2a/pgraph/glsl/vsh-prog.c', 'w') as f:
    f.write(content)

print("Saved vsh-prog.c")
