obj-y += nv2a.o
obj-y += debug.o
obj-y += pbus.o
obj-y += pcrtc.o
obj-y += pfb.o
obj-y += pfifo.o
obj-y += pgraph.o
obj-y += pmc.o
obj-y += pramdac.o
obj-y += prmcio.o
obj-y += prmvio.o
obj-y += psh.o
obj-y += ptimer.o
obj-y += pvideo.o
obj-y += shaders.o
obj-y += stubs.o
obj-y += user.o
obj-y += vsh.o

obj-y += gl/
obj-y += lru.o
obj-y += swizzle.o
obj-y += xxhash.o
xxhash.o-cflags := -O3 -DXXH_FORCE_MEMORY_ACCESS=2
