[CmdletBinding()]
param(
    [string]$Source = "",
    [string]$Output = "",
    [string]$Fxc = ""
)

$ErrorActionPreference = "Stop"
$ExpectedSdkVersion = "10.0.26100.0"
if (-not $Source) { $Source = Join-Path $PSScriptRoot "draw_shaders.hlsl" }
if (-not $Output) { $Output = Join-Path $PSScriptRoot "draw_shaders.h" }

function Resolve-Fxc {
    param([string]$Requested)
    if ($Requested) {
        $candidate = (Resolve-Path -LiteralPath $Requested -ErrorAction Stop).Path
        if ((Split-Path -Leaf $candidate) -ine "fxc.exe") { throw "-Fxc must name fxc.exe" }
        if ($candidate -notmatch "\\bin\\$([regex]::Escape($ExpectedSdkVersion))\\x64\\fxc\.exe$") {
            throw "-Fxc must point to Windows SDK $ExpectedSdkVersion x64 fxc.exe"
        }
        return $candidate
    }
    $command = Get-Command fxc.exe -ErrorAction SilentlyContinue
    if ($command -and $command.Source -match "\\bin\\$([regex]::Escape($ExpectedSdkVersion))\\x64\\fxc\.exe$") {
        return $command.Source
    }
    $kitFxc = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin\$ExpectedSdkVersion\x64\fxc.exe"
    if (Test-Path -LiteralPath $kitFxc -PathType Leaf) { return $kitFxc }
    throw "fxc.exe for Windows SDK $ExpectedSdkVersion x64 not found; pass -Fxc to that exact tool."
}

function Convert-ToCArray {
    param([byte[]]$Bytes)
    $lines = New-Object System.Collections.Generic.List[string]
    for ($offset = 0; $offset -lt $Bytes.Length; $offset += 16) {
        $end = [Math]::Min($offset + 16, $Bytes.Length)
        $items = for ($i = $offset; $i -lt $end; ++$i) { "0x{0:x2}" -f $Bytes[$i] }
        [void]$lines.Add("    " + ($items -join ", ") + ",")
    }
    return ($lines -join "`n")
}

$sourcePath = (Resolve-Path -LiteralPath $Source -ErrorAction Stop).Path
$outputPath = [IO.Path]::GetFullPath($Output)
$fxcPath = Resolve-Fxc $Fxc
$sdkVersion = $ExpectedSdkVersion
$temp = Join-Path ([IO.Path]::GetTempPath()) ("xemu-fxc-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $temp | Out-Null
try {
    # Compile and hash canonical LF/UTF-8 source so checkout line-ending
    # settings cannot change the embedded provenance or DXBC artifact.
    $sourceText = [IO.File]::ReadAllText($sourcePath)
    $sourceText = $sourceText.Replace("`r`n", "`n").Replace("`r", "`n")
    $normalizedSourcePath = Join-Path $temp "draw_shaders.hlsl"
    [IO.File]::WriteAllText($normalizedSourcePath, $sourceText,
                            (New-Object Text.UTF8Encoding($false)))
    $vsPath = Join-Path $temp "draw_vs.dxbc"
    $psPath = Join-Path $temp "draw_ps.dxbc"
    & $fxcPath /nologo /T vs_5_0 /E vs_main /O3 /Fo $vsPath $normalizedSourcePath
    if ($LASTEXITCODE -ne 0) { throw "fxc vertex shader failed ($LASTEXITCODE)" }
    & $fxcPath /nologo /T ps_5_0 /E ps_main /O3 /Fo $psPath $normalizedSourcePath
    if ($LASTEXITCODE -ne 0) { throw "fxc pixel shader failed ($LASTEXITCODE)" }
    $sourceBytes = [Text.Encoding]::UTF8.GetBytes($sourceText)
    $vsBytes = [IO.File]::ReadAllBytes($vsPath)
    $psBytes = [IO.File]::ReadAllBytes($psPath)
    $sha = [Security.Cryptography.SHA256]::Create()
    $sourceHash = ([BitConverter]::ToString($sha.ComputeHash($sourceBytes))).Replace("-", "").ToLowerInvariant()
    $vsHash = ([BitConverter]::ToString($sha.ComputeHash($vsBytes))).Replace("-", "").ToLowerInvariant()
    $psHash = ([BitConverter]::ToString($sha.ComputeHash($psBytes))).Replace("-", "").ToLowerInvariant()
    $content = @"
// Generated by draw_shaders.ps1; do not edit.
// Source SHA-256: $sourceHash
// VS DXBC SHA-256: $vsHash
// PS DXBC SHA-256: $psHash
// Compiler: fxc.exe; Windows SDK $sdkVersion
#ifndef XEMU_NV2A_PGRAPH_D3D11_DRAW_SHADERS_H
#define XEMU_NV2A_PGRAPH_D3D11_DRAW_SHADERS_H

#include <stddef.h>

namespace xemu {
namespace d3d11_draw_shaders {
static const unsigned char kVertexShader[] = {
$(Convert-ToCArray $vsBytes)
};
static const size_t kVertexShaderSize = sizeof(kVertexShader);
static const unsigned char kPixelShader[] = {
$(Convert-ToCArray $psBytes)
};
static const size_t kPixelShaderSize = sizeof(kPixelShader);
} // namespace d3d11_draw_shaders
} // namespace xemu

#endif // XEMU_NV2A_PGRAPH_D3D11_DRAW_SHADERS_H
"@
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($outputPath)) | Out-Null
    [IO.File]::WriteAllText($outputPath, $content.Replace("`r`n", "`n"))
    Write-Host "Compiler: fxc.exe; Windows SDK $sdkVersion"
    Write-Host "Source SHA-256: $sourceHash"
    Write-Host "VS DXBC SHA-256: $vsHash"
    Write-Host "PS DXBC SHA-256: $psHash"
} finally {
    if (Test-Path -LiteralPath $temp) { Remove-Item -LiteralPath $temp -Recurse -Force }
}
