[CmdletBinding()]
param([string]$Source = "", [string]$Output = "", [string]$Fxc = "")
$ErrorActionPreference = "Stop"
if (-not $Source) { $Source = Join-Path $PSScriptRoot "psh_interpreter.hlsl" }
if (-not $Output) { $Output = Join-Path $PSScriptRoot "psh_interpreter_shaders.h" }
function Resolve-Fxc([string]$Requested) {
    if ($Requested) { return (Resolve-Path -LiteralPath $Requested -ErrorAction Stop).Path }
    $cmd = Get-Command fxc.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $kits = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin"
    $found = Get-ChildItem -LiteralPath $kits -Filter fxc.exe -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -match "\\x64\\fxc\.exe$" } |
        Sort-Object FullName -Descending | Select-Object -First 1
    if ($found) { return $found.FullName }
    throw "fxc.exe not found; install the Windows SDK or pass -Fxc."
}
function CArray([byte[]]$bytes) {
    $lines = New-Object System.Collections.Generic.List[string]
    for ($o=0; $o -lt $bytes.Length; $o+=16) {
        $end=[Math]::Min($o+16,$bytes.Length)
        $items=for($i=$o;$i -lt $end;++$i){"0x{0:x2}" -f $bytes[$i]}
        [void]$lines.Add("    "+($items -join ", ")+",")
    }
    return $lines -join "`n"
}
$src=(Resolve-Path -LiteralPath $Source -ErrorAction Stop).Path; $out=[IO.Path]::GetFullPath($Output); $fxc=Resolve-Fxc $Fxc
$sdkVersion="unknown"; if($fxc -match "\\bin\\([^\\]+)\\x64\\fxc\.exe$"){ $sdkVersion=$Matches[1] }
$tmp=Join-Path ([IO.Path]::GetTempPath()) ("xemu-psh-fxc-"+[guid]::NewGuid().ToString("N")); New-Item -ItemType Directory -Path $tmp | Out-Null
try {
    $normalized=Join-Path $tmp "source.hlsl"
    $sourceText=[IO.File]::ReadAllText($src); $sourceText=$sourceText.Replace("`r`n","`n").Replace("`r","`n")
    [IO.File]::WriteAllText($normalized,$sourceText,(New-Object Text.UTF8Encoding($false)))
    $vs=Join-Path $tmp "vs.dxbc"; $ps=Join-Path $tmp "ps.dxbc"
    & $fxc /nologo /T vs_5_0 /E vs_main /O3 /Fo $vs $normalized; if($LASTEXITCODE){throw "fxc VS failed ($LASTEXITCODE)"}
    & $fxc /nologo /T ps_5_0 /E ps_main /O3 /Fo $ps $normalized; if($LASTEXITCODE){throw "fxc PS failed ($LASTEXITCODE)"}
    $sha=[Security.Cryptography.SHA256]::Create(); $sh=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($sourceText)))).Replace("-","").ToLowerInvariant(); $vh=([BitConverter]::ToString($sha.ComputeHash([IO.File]::ReadAllBytes($vs)))).Replace("-","").ToLowerInvariant(); $ph=([BitConverter]::ToString($sha.ComputeHash([IO.File]::ReadAllBytes($ps)))).Replace("-","").ToLowerInvariant()
    $text="// Generated by psh_interpreter.ps1; do not edit.`n// Source SHA-256: $sh`n// VS DXBC SHA-256: $vh`n// PS DXBC SHA-256: $ph`n// Compiler: fxc.exe; Windows SDK $sdkVersion`n#ifndef XEMU_NV2A_PGRAPH_D3D11_PSH_INTERPRETER_SHADERS_H`n#define XEMU_NV2A_PGRAPH_D3D11_PSH_INTERPRETER_SHADERS_H`n#include <stddef.h>`nnamespace xemu { namespace d3d11_psh { static const unsigned char kVertexShader[] = {`n$(CArray ([IO.File]::ReadAllBytes($vs)))`n}; static const size_t kVertexShaderSize=sizeof(kVertexShader); static const unsigned char kPixelShader[]={`n$(CArray ([IO.File]::ReadAllBytes($ps)))`n}; static const size_t kPixelShaderSize=sizeof(kPixelShader); } }`n#endif`n"
    [IO.File]::WriteAllText($out,$text.Replace("`r`n","`n")); Write-Host "Compiler: fxc.exe; Windows SDK $sdkVersion"; Write-Host "Source SHA-256: $sh"; Write-Host "VS DXBC SHA-256: $vh"; Write-Host "PS DXBC SHA-256: $ph"
} finally { if(Test-Path -LiteralPath $tmp){Remove-Item -LiteralPath $tmp -Recurse -Force} }
