[CmdletBinding()]
param(
    [string]$Source = "",
    [string]$Output = "",
    [string]$Fxc = ""
)

$ErrorActionPreference = "Stop"
$ExpectedSdkVersion = "10.0.26100.0"
if (-not $Source) { $Source = Join-Path $PSScriptRoot "vsh_cpu_passthrough.hlsl" }
if (-not $Output) { $Output = Join-Path $PSScriptRoot "vsh_cpu_passthrough.h" }

function Resolve-Fxc {
    param([string]$Requested)
    if ($Requested) {
        $candidate = (Resolve-Path -LiteralPath $Requested -ErrorAction Stop).Path
        if ((Split-Path -Leaf $candidate) -ine "fxc.exe") { throw "-Fxc must name fxc.exe" }
        if ($candidate -notmatch "\\bin\\$([regex]::Escape($ExpectedSdkVersion))\\x64\\fxc\.exe$") {
            throw "-Fxc must point to Windows SDK $ExpectedSdkVersion x64 fxc.exe"
        }
        return $candidate
    }
    $command = Get-Command fxc.exe -ErrorAction SilentlyContinue
    if ($command -and
        $command.Source -match "\\bin\\$([regex]::Escape($ExpectedSdkVersion))\\x64\\fxc\.exe$") {
        return $command.Source
    }
    $kitFxc = Join-Path ${env:ProgramFiles(x86)} "Windows Kits\10\bin\$ExpectedSdkVersion\x64\fxc.exe"
    if (Test-Path -LiteralPath $kitFxc -PathType Leaf) { return $kitFxc }
    throw "fxc.exe for Windows SDK $ExpectedSdkVersion x64 not found; pass -Fxc to that exact tool."
}

function Convert-ToCArray {
    param([byte[]]$Bytes)
    $lines = New-Object System.Collections.Generic.List[string]
    for ($offset = 0; $offset -lt $Bytes.Length; $offset += 16) {
        $end = [Math]::Min($offset + 16, $Bytes.Length)
        $items = for ($i = $offset; $i -lt $end; ++$i) { "0x{0:x2}" -f $Bytes[$i] }
        [void]$lines.Add("    " + ($items -join ", ") + ",")
    }
    return ($lines -join "`n")
}

$sourcePath = (Resolve-Path -LiteralPath $Source -ErrorAction Stop).Path
$outputPath = [IO.Path]::GetFullPath($Output)
$fxcPath = Resolve-Fxc $Fxc
$sdkVersion = "unknown"
if ($fxcPath -match "\\bin\\([^\\]+)\\x64\\fxc\.exe$") {
    $sdkVersion = $Matches[1]
}
if ($sdkVersion -ne $ExpectedSdkVersion) {
    throw "FXC SDK mismatch: expected $ExpectedSdkVersion, got $sdkVersion"
}
$temp = Join-Path ([IO.Path]::GetTempPath()) ("xemu-fxc-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $temp | Out-Null
try {
    $vsPath = Join-Path $temp "vsh_cpu_passthrough_vs.dxbc"
    & $fxcPath /nologo /WX /T vs_5_0 /E vs_main /O3 /Fo $vsPath $sourcePath
    if ($LASTEXITCODE -ne 0) { throw "fxc vertex shader failed ($LASTEXITCODE)" }
    $sourceBytes = [IO.File]::ReadAllBytes($sourcePath)
    $vsBytes = [IO.File]::ReadAllBytes($vsPath)
    $sha = [Security.Cryptography.SHA256]::Create()
    $sourceHash = ([BitConverter]::ToString($sha.ComputeHash($sourceBytes))).Replace("-", "").ToLowerInvariant()
    $vsHash = ([BitConverter]::ToString($sha.ComputeHash($vsBytes))).Replace("-", "").ToLowerInvariant()
    $content = @"
// Generated by vsh_cpu_passthrough.ps1; do not edit.
// Source SHA-256: $sourceHash
// VS DXBC SHA-256: $vsHash
// Compiler: fxc.exe; Windows SDK $sdkVersion (enforced)
#ifndef XEMU_NV2A_PGRAPH_D3D11_VSH_CPU_PASSTHROUGH_H
#define XEMU_NV2A_PGRAPH_D3D11_VSH_CPU_PASSTHROUGH_H

#include <stddef.h>

namespace xemu {
namespace d3d11_vsh_cpu_passthrough {
static const unsigned char kVertexShader[] = {
$(Convert-ToCArray $vsBytes)
};
static const size_t kVertexShaderSize = sizeof(kVertexShader);
} // namespace d3d11_vsh_cpu_passthrough
} // namespace xemu

#endif // XEMU_NV2A_PGRAPH_D3D11_VSH_CPU_PASSTHROUGH_H
"@
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($outputPath)) | Out-Null
    [IO.File]::WriteAllText($outputPath, $content.Replace("`r`n", "`n"))
    Write-Host "Compiler: fxc.exe; Windows SDK $sdkVersion"
    Write-Host "Source SHA-256: $sourceHash"
    Write-Host "VS DXBC SHA-256: $vsHash"
} finally {
    if (Test-Path -LiteralPath $temp) { Remove-Item -LiteralPath $temp -Recurse -Force }
}
