include:
  - local: '/.gitlab-ci.d/container-template.yml'

amd64-centos8-container:
  extends: .container_job_template
  variables:
    NAME: centos8

amd64-fedora-container:
  extends: .container_job_template
  variables:
    NAME: fedora
